<a href="https://colab.research.google.com/github/dushyantsinghpawar/EuropeanSoccer/blob/main/EST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# European Soccer Database: Data Description

---

**Overview:**  
The European Soccer Database provides a comprehensive dataset for data analysis and machine learning applications in the context of professional football (soccer). This dataset consolidates information on matches, players, teams, and game events across European leagues from 2008 to 2016. It offers rich features sourced from multiple authoritative sources, making it an ideal resource for predictive modeling, statistical analysis, and exploratory data analysis.

---

**Dataset Features:**  
1. **Matches & Players**  
   - Over 25,000 matches and 10,000 players across 11 European countries, focusing on their lead championships.  
   - Detailed match events for 10,000+ matches, including goal types, possession, corners, crosses, fouls, and cards.  

2. **Time Frame**  
   - Covers football seasons from 2008 to 2016.  

3. **Attributes Sourced from FIFA Video Game Series**  
   - Players' and teams' attributes are derived from EA Sports FIFA's weekly updates.  
   - Attributes include team formations, player statistics, and performance metrics.

4. **Spatial Data**  
   - Team lineups and squad formations are provided using (X, Y) coordinate data.

5. **Betting Odds**  
   - Odds from up to 10 providers are included for matches, enabling probability analysis and comparison with machine-learning predictions.

6. **Improvements in Progress**  
   - Efforts are ongoing to include missing player data, international games, national cups, and tournaments like the Champions League and Europa League.  

---

**Data Sources:**  
- Match scores, lineup details, and in-game events: [football-data.mx-api.enetscores.com](http://football-data.mx-api.enetscores.com/)  
- Betting odds: [football-data.co.uk](http://www.football-data.co.uk/)  
- FIFA player and team attributes: [sofifa.com](http://sofifa.com/)  

---

**Applications:**  
- **Outcome Prediction:**  
   - Build machine learning models (e.g., SVM) to predict match outcomes (Home Win, Draw, Away Win).  
   - Analyze probabilities vs betting odds for variance analysis.

- **Feature Exploration:**  
   - Explore player attributes, team formations, and match events to uncover patterns and insights in football data.  

- **Data Visualization:**  
   - Create visualizations to better understand the dynamics of matches, team strategies, and player performance.

---

**Future Directions:**  
- Address missing player attributes using improved crawling algorithms.  
- Expand the dataset to include additional competitions and international tournaments.  
- Provide updated crawling scripts compatible with website changes.  

---

**Note:**  
The dataset is intended strictly for research and non-commercial purposes. For details, visit the [GitHub repository](https://github.com/hugomathien/football-data-collection).

##Extracting Data from a SQLite Database to a CSV version

In [ ]:
#Check tables present in the Database (Data used: "https://www.kaggle.com/datasets/hugomathien/soccer")
import sqlite3
import pandas as pd

# Connect to SQLite database
MasterData = sqlite3.connect('/content/database.sqlite')  # Replace with your SQLite file name

# List all table names
tables_query = "SELECT name FROM sqlite_master WHERE type='table';"
tables = pd.read_sql_query(tables_query, MasterData)
print("Tables in the database:")
print(tables)

Tables in the database:
                name
0    sqlite_sequence
1  Player_Attributes
2             Player
3              Match
4             League
5            Country
6               Team
7    Team_Attributes

###Reading data from different tables

In [ ]:
#Player name
player_q = "SELECT * FROM Player"
player = pd.read_sql_query(player_q, MasterData)

#Player attribute
player_a = "SELECT * FROM Player_Attributes"
playerattributes = pd.read_sql_query(player_a, MasterData)

#Team
team_q = "SELECT * FROM Team"
teamname = pd.read_sql_query(team_q, MasterData)

#Match
match_q = "SELECT * FROM Match"
match = pd.read_sql_query(match_q, MasterData)

#League
league_q = "SELECT * FROM League"
league = pd.read_sql_query(league_q, MasterData)

#Country
country_q = "SELECT * FROM Country"
country = pd.read_sql_query(country_q, MasterData)

In [ ]:
print('Player')
player.head(5)

In [ ]:
print('Player Attributes')
playerattributes.head(5)

Player Attributes

,id,player_fifa_api_id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,1,218353,505942,2016-02-18 00:00:00,67.0,71.0,right,medium,medium,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,2,218353,505942,2015-11-19 00:00:00,67.0,71.0,right,medium,medium,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,3,218353,505942,2015-09-21 00:00:00,62.0,66.0,right,medium,medium,49.0,...,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,4,218353,505942,2015-03-20 00:00:00,61.0,65.0,right,medium,medium,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,5,218353,505942,2007-02-22 00:00:00,61.0,65.0,right,medium,medium,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0

In [ ]:
print('Team Details')
teamname.head(5)

In [ ]:
print('Match Details')
match.head(5)

Match Details

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,...,4.00,1.65,3.40,4.50,1.78,3.25,4.00,1.73,3.40,4.20
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,...,3.80,2.00,3.25,3.25,1.85,3.25,3.75,1.91,3.25,3.60
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,...,2.50,2.35,3.25,2.65,2.50,3.20,2.50,2.30,3.20,2.75
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,...,7.50,1.45,3.75,6.50,1.50,3.75,5.50,1.44,3.75,6.50
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,...,1.73,4.50,3.40,1.65,4.50,3.50,1.65,4.75,3.30,1.67

In [ ]:
print('League Details')
league.head(5)

In [ ]:
print('Country Details')
country.head(5)

###Converting Table Data to "csv" format

In [ ]:
player.to_csv('player.csv', index=False)
playerattributes.to_csv('playerattributes.csv', index=False)
teamname.to_csv('teamname.csv', index=False)
match.to_csv('match.csv', index=False)
league.to_csv('league.csv', index=False)
country.to_csv('country.csv', index=False)